name = "resistorcolor-worker"
main = "src/index.js"
compatibility_date = "2023-10-25"

# Serve static assets from the public directory
assets = { directory = "./public", binding = "ASSETS" }

# KV namespace for storing learned color definitions
[[kv_namespaces]]
binding = "LEARNING_STORE"
id = "5cf5788ef3b645e1b0f544d2abe6b8cb"
preview_id = ""